steps:
- name: 'gcr.io/cloud-builders/go'
  id: 'Run Test'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/go'
  id: 'Build Image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$:$SHORT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$:$SHORT_SHA']